### ISSUE TITLE
Errors when running ar.py on Win10

### ISSUE THREAD

**Issue by JBOE22175** [jdb78/pytorch-forecasting#9] opened 2020-08-21 10:35 UTC
Hi, 
I appreciate your work to provied a package for TFT using pytorch. I just succesfuly run the google AIHUB-implemaentation and would be happy to use a PyTorch version which seems to be somewhat easier. 
 
But, so far I am not able to run even a simple example without problems on Windows 10 without GPU.
It would be great if you could provide an easy starting point into your development. It would help a lot to contribute to your project.

## Installation: 
I created an enironment with Python version 3.7.8.
After pip install pytorch-forecasting I got this error:
`ERROR: Could not find a version that satisfies the requirement torch<2.0,>=1.6 (from pytorch-forecasting) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
RROR: No matching distribution found for torch<2.0,>=1.6 (from pytorch-forecasting)`

Nevertheless, when I install pytorch first (conda install pytorch torchvision cpuonly -c pytorch) then pytorch-forecasting got installed w/o problems and required versions were installed - among other:
`optuna                        2.0.0
pandas                        1.1.0
pytorch-forecasting           0.2.0
pytorch-lightning             0.8.5
pytorch-ranger                0.1.1
scikit-learn                  0.23.2
scipy                         1.5.2
statsmodels                   0.11.1
torch                         1.6.0`

## Running an example
Your github README.md does not provide a directly executable example (data is missing). Thus I tried ar.py. 
First obstacle is that you need `generate_ar_data formexample/data/__init__.py` which is not installed via above pip install procedure.  A local copy in `example_data.py` with 
```
#from data import generate_ar_data
from example_data import generate_ar_data
```
helped to overcome this.

**TimeSeriesDataSet** reported an error which led to following correction:	
```
#data["static"] = 2
data["static"] = '2'   #must be string
```
**pl.Trainer** 
GPU available: False, used: False
TPU available: False, using: 0 TPU cores

**TemporalFusionTransformer.from_dataset**
Number of parameters in network: 76.6k

**trainer.fit** results in following list:

 n  | Name                               | Type                            | Params
---| --------------------------| ------------------------| -----------------------------------
0  | loss                               | QuantileLoss                    | 0     
1  | input_embeddings                   | ModuleDict                      | 1     
2  | prescalers                         | ModuleDict                      | 256   
3  | static_variable_selection          | VariableSelectionNetwork        | 9 K   
4  | encoder_variable_selection         | VariableSelectionNetwork        | 8 K   
5  | decoder_variable_selection         | VariableSelectionNetwork        | 4 K   
6  | static_context_variable_selection  | GatedResidualNetwork            | 4 K   
7  | static_context_initial_hidden_lstm | GatedResidualNetwork            | 4 K   
8  | static_context_initial_cell_lstm   | GatedResidualNetwork            | 4 K   
9  | static_context_enrichment          | GatedResidualNetwork            | 4 K   
10 | lstm_encoder                       | LSTM                            | 8 K   
11 | lstm_decoder                       | LSTM                            | 8 K   
12 | post_lstm_gate_encoder             | GatedLinearUnit                 | 2 K   
13 | post_lstm_add_norm_encoder         | AddNorm                         | 64    
14 | static_enrichment                  | GatedResidualNetwork            | 5 K   
15 | multihead_attn                     | InterpretableMultiHeadAttention | 4 K   
16 | post_attn_gate_norm                | GateAddNorm                     | 2 K   
17 | pos_wise_ff                        | GatedResidualNetwork            | 4 K   
18 | pre_output_gate_norm               | GateAddNorm                     | 2 K   
19 | output_layer                       | Linear                          | 99    
---------------------------------------------------------------------------
Validation sanity check: 0it [00:00, ?it/s]

**and following RuntiemError:**

RuntimeError                              Traceback (most recent call last)
<ipython-input-12-f13d4d95ac28> in <module>
     12 torch.set_num_threads(10)
     13 trainer.fit(
---> 14     tft, train_dataloader=train_dataloader, val_dataloaders=val_dataloader,
     15 )

~\miniconda3\envs\tft\lib\site-packages\pytorch_lightning\trainer\trainer.py in fit(self, model, train_dataloader, val_dataloaders)
   1042             self.optimizers, self.lr_schedulers, self.optimizer_frequencies = self.init_optimizers(model)
   1043 
-> 1044             results = self.run_pretrain_routine(model)
   1045 
   1046         # callbacks

~\miniconda3\envs\tft\lib\site-packages\pytorch_lightning\trainer\trainer.py in run_pretrain_routine(self, model)
   1194                                           self.val_dataloaders,
   1195                                           max_batches,
-> 1196                                           False)
   1197 
   1198             # allow no returns from eval

~\miniconda3\envs\tft\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py in _evaluate(self, model, dataloaders, max_batches, test_mode)
    291                         output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
    292                 else:
--> 293                     output = self.evaluation_forward(model, batch, batch_idx, dataloader_idx, test_mode)
    294 
    295                 # on dp / ddp2 might still want to do something with the batch parts

~\miniconda3\envs\tft\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py in evaluation_forward(self, model, batch, batch_idx, dataloader_idx, test_mode)
    468             output = model.test_step(*args)
    469         else:
--> 470             output = model.validation_step(*args)
    471 
    472         return output

~\miniconda3\envs\tft\lib\site-packages\pytorch_forecasting\models\base_model.py in validation_step(self, batch, batch_idx)
    143     def validation_step(self, batch, batch_idx):
    144         x, y = batch
--> 145         log, _ = self.step(x, y, batch_idx, label="val")
    146         return log
    147 

~\miniconda3\envs\tft\lib\site-packages\pytorch_forecasting\models\temporal_fusion_transformer\__init__.py in step(self, x, y, batch_idx, label)
    572         # extract data and run model
    573         y = rnn.pack_padded_sequence(y, lengths=x["decoder_lengths"], batch_first=True, enforce_sorted=False)
--> 574         log, out = super().step(x, y, batch_idx, label=label)
    575         # calculate interpretations etc for latter logging
    576         if self.log_interval(label == "train") > 0:

~\miniconda3\envs\tft\lib\site-packages\pytorch_forecasting\models\base_model.py in step(self, x, y, batch_idx, label)
    185             loss = self.loss(prediction, y) * (1 + monotinicity_loss)
    186         else:
--> 187             out = self(x)
    188             out["prediction"] = self.transform_output(out)
    189 

~\miniconda3\envs\tft\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~\miniconda3\envs\tft\lib\site-packages\pytorch_forecasting\models\temporal_fusion_transformer\__init__.py in forward(self, x)
    445                 )
    446             else:
--> 447                 input_vectors[name] = emb(x_cat[..., self.hparams.x_categoricals.index(name)])
    448         input_vectors.update({name: x_cont[..., idx].unsqueeze(-1) for idx, name in enumerate(self.hparams.x_reals)})
    449 

~\miniconda3\envs\tft\lib\site-packages\torch\nn\modules\module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~\miniconda3\envs\tft\lib\site-packages\torch\nn\modules\sparse.py in forward(self, input)
    124         return F.embedding(
    125             input, self.weight, self.padding_idx, self.max_norm,
--> 126             self.norm_type, self.scale_grad_by_freq, self.sparse)
    127 
    128     def extra_repr(self) -> str:

~\miniconda3\envs\tft\lib\site-packages\torch\nn\functional.py in embedding(input, weight, padding_idx, max_norm, norm_type, scale_grad_by_freq, sparse)
   1812         # remove once script supports set_grad_enabled
   1813         _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
-> 1814     return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
   1815 
   1816 

RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.IntTensor instead (while checking arguments for embedding)

**Comment by jdb78** [comment] 2020-08-23 18:27
I have (hopefully) fixed the issue. Testing on windows turns out to be more complicated than anticipated but should be possible once poetry releases an update. For the moment being, you have to first install pytorch and then pytorch-forecasting. The issue is that pytorch does not provide wheels for Windows on PyPI.

**Comment by jdb78** [comment] 2020-08-25 22:30
Closing this as there were numerous fixed to the package - thanks again for reporting this issue! Please feel encouraged to raise a new issue in case you encounter any bugs.

**Closed by jdb78** 2020-08-25 22:30 UTC
